# Generated by Django 5.0.3 on 2024-03-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_alter_menu_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
