# Generated by Django 5.0.3 on 2024-03-22 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_rename_url_menu_url_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url_field',
            field=models.URLField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
