# Generated by Django 5.0.3 on 2024-03-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_alter_menu_url_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url_field',
            field=models.URLField(),
        ),
    ]
