# Generated by Django 5.0.3 on 2024-03-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_categories_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='depth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='numchild',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categories',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
